# Generated by Django 5.2 on 2025-04-18 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_product_id_slug_products_pr_id_a08e3c_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_morrisons',
            new_name='price_amazon',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price_sainsburys',
            new_name='price_flipkart',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price_tesco',
            new_name='price_myntra',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='url_morrisons',
            new_name='url_amazon',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='url_sainsburys',
            new_name='url_flipkart',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='url_tesco',
            new_name='url_myntra',
        ),
    ]
